name: eoog
description: "sns_app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_code_metrics: ^5.7.6
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  get_it: ^7.6.7
  go_router: ^14.2.1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  mocktail: ^1.0.4
  retrofit: ^4.1.0

  flutter_native_splash: ^2.4.1
  icons_launcher: ^2.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true
  ## 이미지들 넣는곳
  assets:
    - assets/
    - assets/svg/
    - assets/icon/
    - assets/image/

icons_launcher:
  image_path: assets/icon/androidAppIcon.png
  platforms:
    android:
      enable: true
      adaptive_background_color: "#4F0504"
      adaptive_foreground_image: assets/icon/androidAppIcon.png
      adaptive_round_image: assets/icon/androidAppIcon.png
    ios:
      enable: true
      image_path: assets/icon/iOSAppIcon.png

flutter_native_splash:
  color: "#4F0504"
  image: assets/icon/splash.png
  color_dark: "#4F0504"
  image_dark: assets/icon/splash.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#4F0504"
    image: assets/icon/android12Splash.png
    icon_background_color: "#4F0504"
    color_dark: "#4F0504"
    image_dark: assets/icon/android12Splash.png
    icon_background_color_dark: "#4F0504"
  android_gravity: center
  ios_content_mode: center